Feat/30 monitoring
f-lab-clone/ticketing-infra pull request #36
Opened 2023-08-27 09:48 UTC by junha-ahn

#  What is this PR?
- Github Issue: #30 

# Key Changes
- install [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/README.md)

# Test Checklist

2023-09-06 11:31 UTC, junha-ahn reviewed
프동프동 인프라 역사상 최고의 커밋

2023-09-10 14:19 UTC, hihahayoung requested changes

2023-09-10 14:19 UTC, hihahayoung commented on src/grafana/kube_prometheus_custom_values.yaml
> +          - targets: ["172.20.75.91:9104"]
k8s **DNS**를 이용 (DNS for Services)
- `172.20.75.91:9104` => `mysql....-service.com:9104`

2023-09-10 14:19 UTC, hihahayoung commented on src/grafana/mysql_exporter_custom_values.yaml
`src/mysql` 폴더 생성 후 

`user.sql` 파일 생성

```sql
CREATE USER 'exporter'@'%' IDENTIFIED BY 'pw1234' WITH MAX_USER_CONNECTIONS 3;
GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';
```

2023-09-10 14:19 UTC, hihahayoung commented on src/grafana/dashboards/test_dashboard.json
(연습용) 대시보드에 MySQL cpu + memory usage 추가

2023-09-11 05:32 UTC, merged